# Generated by Django 5.2.12 on 2026-04-27 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainXHostel_app', '0002_leaveapplication_delete_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='parent_contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='student_contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
