# Generated by Django 5.2.12 on 2026-04-28 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainXHostel_app', '0004_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='id_proof',
            field=models.FileField(upload_to='visitors/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
