# Generated by Django 5.2.12 on 2026-04-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainXHostel_app', '0005_alter_visitor_id_proof_alter_visitor_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
