# Generated by Django 5.2.12 on 2026-05-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainXHostel_app', '0008_student_removed_at_student_removed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
    ]
