# Generated by Django 5.2.12 on 2026-05-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainXHostel_app', '0009_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room_type',
            field=models.CharField(choices=[('AC', 'AC'), ('NON_AC', 'Non AC')], default='NON_AC', max_length=10),
        ),
    ]
