# Generated by Django 5.2.12 on 2026-05-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplainXHostel_app', '0010_student_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room_type',
        ),
    ]
